var game = {
    cashBalance: new Decimal(0),
    tokenBalance: new Decimal(0),
    tier1CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(1.8),
        costAddend: new Decimal(0),
    },
    tier2CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(4.7),
        costAddend: new Decimal(10000),
    },
    tier3CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(7.55),
        costAddend: new Decimal(7777777),
    },
    tier4CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(12.425),
        costAddend: new Decimal(1212312345),
    },
    tier5CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(17.3),
        costAddend: new Decimal("2e14"),
    },
    tier6CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(25),
        costAddend: new Decimal("1.81818e18"),
    },
    tier7CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(39.4),
        costAddend: new Decimal("2.22222e22"),
    },
    tier8CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(55.55),
        costAddend: new Decimal("9e27"),
    },
    tier9CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(77.77),
        costAddend: new Decimal("5e40"),
    },
    tier10CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(123.456789),
        costAddend: new Decimal("1e100"),
    },
    tier1TokenGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(5),
        costAddend: new Decimal("100"),
    },
    tier2TokenGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(5),
        costAddend: new Decimal("100"),
    },
    tier3TokenGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        totalObtained: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: new Decimal(5),
        costAddend: new Decimal("100"),
    },
}