var game = {
    cashBalance: new Decimal(0),
    tokenBalance: new Decimal(0),
    tier1CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: 1.8,
    },
    tier2CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: 4.7,
    },
    tier3CashGenerator : {
        totalOwned: new Decimal(0),
        totalPurchased: new Decimal(0),
        totalGenerated: new Decimal(0),
        productionMultiplier: new Decimal(0),
        totalProduction: new Decimal(0),
        productionPerGenerator: new Decimal(0),
        costExponent: 7.55,
    },
}